# Generated by Django 2.2 on 2019-09-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('nickname', models.TextField()),
                ('race', models.TextField()),
                ('profession', models.TextField()),
                ('strength', models.PositiveSmallIntegerField()),
                ('mana', models.PositiveSmallIntegerField()),
                ('HP', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
