# Generated by Django 2.2 on 2019-10-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroCreator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='nickname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='profession',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.TextField(blank=True, null=True),
        ),
    ]
