# Generated by Django 2.2 on 2019-10-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroCreator', '0002_auto_20191001_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
