# Generated by Django 2.2 on 2019-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroCreator', '0004_auto_20191002_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
