# Generated by Django 2.2 on 2019-10-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroCreator', '0005_auto_20191002_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
