# Generated by Django 2.2.5 on 2019-10-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroCreator', '0006_hero_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hero',
            name='nickname',
            field=models.CharField(default=3123, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hero',
            name='profession',
            field=models.CharField(default=31231412, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.CharField(default=2131241243, max_length=30),
            preserve_default=False,
        ),
    ]
