# Generated by Django 2.2.6 on 2019-12-26 09:12

from django.db import migrations, models
import heroCreator.models


class Migration(migrations.Migration):

    dependencies = [
        ('heroCreator', '0008_hero_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='story',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hero',
            name='HP',
            field=models.PositiveSmallIntegerField(default=heroCreator.models.Hero.hpRandomizer),
        ),
        migrations.AlterField(
            model_name='hero',
            name='mana',
            field=models.PositiveSmallIntegerField(default=heroCreator.models.Hero.manaRandomizer),
        ),
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.CharField(choices=[('Ogre', 'Ogre'), ('Human', 'Human'), ('Elf', 'Elf'), ('Gnome', 'Gnome'), ('Hobbit', 'Hobbit'), ('Dwarf', 'Dwarf'), ('None', 'None')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strength',
            field=models.PositiveSmallIntegerField(default=heroCreator.models.Hero.strengthRandomizer),
        ),
    ]
