# Generated by Django 2.2.6 on 2019-12-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroCreator', '0009_auto_20191226_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.CharField(choices=[('Dwarf', 'Dwarf'), ('Gnome', 'Gnome'), ('Ogre', 'Ogre'), ('Hobbit', 'Hobbit'), ('None', 'None'), ('Elf', 'Elf'), ('Human', 'Human')], default=0, max_length=30),
        ),
    ]
