# Generated by Django 2.2.6 on 2019-12-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroCreator', '0010_auto_20191226_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.CharField(choices=[('Human', 'Human'), ('Gnome', 'Gnome'), ('Elf', 'Elf'), ('Ogre', 'Ogre'), ('Hobbit', 'Hobbit'), ('None', 'None'), ('Dwarf', 'Dwarf')], default=0, max_length=30),
        ),
    ]
