# Generated by Django 2.2.6 on 2019-12-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroCreator', '0011_auto_20191226_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.CharField(choices=[('Hobbit', 'Hobbit'), ('Human', 'Human'), ('Ogre', 'Ogre'), ('Dwarf', 'Dwarf'), ('Gnome', 'Gnome'), ('Elf', 'Elf'), ('None', 'None')], default=0, max_length=30),
        ),
    ]
