# Generated by Django 2.2.6 on 2019-12-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroCreator', '0012_auto_20191226_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='classes',
            field=models.CharField(choices=[('Priest', 'Priest'), ('Warlock', 'Warlock'), ('Hunter', 'Hunter'), ('Rouge', 'Rouge'), ('Druid', 'Druid'), ('Mage', 'Mage'), ('Palladin', 'Palladin'), ('Warrior', 'Warrior')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.CharField(choices=[('Ogre', 'Ogre'), ('Elf', 'Elf'), ('Human', 'Human'), ('Hobbit', 'Hobbit'), ('None', 'None'), ('Gnome', 'Gnome'), ('Dwarf', 'Dwarf')], default=0, max_length=30),
        ),
    ]
